default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: novel-film_development

test:
  <<: *default
  database: novel-film_test

production:
  <<: *default
  database: novel-film_production
  username: cmchavez
  password: <%= ENV['12345'] %>